const { GoogleGenAI } = require("@google/genai");

// Fallback Mock Database for offline use or API failures
const MOCK_FACTS = {
  platypus: [
    {
      fact: "Male platypuses have a venomous spur on the heel of each hind foot. The venom can kill small animals and causes excruciating, long-lasting pain in humans.",
      hint: "Did you know that male platypuses possess a painful weapon on their hind legs?",
      isTrue: true,
      distractor: "Male platypuses spray a blinding chemical liquid from glands under their tails when threatened.",
      source: "https://www.nationalgeographic.com/animals/mammals/facts/platypus",
      citation: "National Geographic: Platypus Guide"
    },
    {
      fact: "Female platypuses secrete milk from sweat glands on their abdominal skin because they lack nipples, leaving the puggle to lick it from their fur.",
      hint: "Did you know that female platypuses feed their babies without having nipples?",
      isTrue: true,
      distractor: "Female platypuses secrete a crop-milk from their bills similar to pigeons.",
      source: "https://www.britannica.com/animal/platypus",
      citation: "Encyclopaedia Britannica: Platypus Facts"
    },
    {
      fact: "Platypuses are electroreceptive; they hunt with eyes, ears, and nostrils closed by sensing the tiny electric fields generated by prey muscles.",
      hint: "Did you know that platypuses hunt with their eyes, ears, and nose completely closed?",
      isTrue: true,
      distractor: "Platypuses emit high-frequency sonar clicks, much like bats, to map dark waters.",
      source: "https://www.scientificamerican.com/article/how-the-platypus-feels-electroreception/",
      citation: "Scientific American: Platypus Electroreception"
    },
    {
      fact: "The platypus does not have a stomach; its esophagus connects directly to its intestines, meaning food is digested without acid or pepsin.",
      hint: "Did you know that platypuses have a highly unusual digestive system that lacks a key organ?",
      isTrue: true,
      distractor: "Platypuses possess three stomachs similar to cows to digest tough shells.",
      source: "https://www.nationalgeographic.com/science/article/how-the-platypus-lost-its-stomach",
      citation: "National Geographic: How the Platypus Lost Its Stomach"
    },
    {
      fact: "The platypus's fur glows a bluish-green color under ultraviolet light, a phenomenon known as biofluorescence.",
      hint: "Did you know that platypuses glow in the dark under specific lighting conditions?",
      isTrue: true,
      distractor: "Platypuses have bioluminescent patches on their chest that attract mates in muddy water.",
      source: "https://www.nytimes.com/2020/10/30/science/platypus-glow-uv-light.html",
      citation: "New York Times: Biofluorescent Platypuses"
    }
  ],
  octopus: [
    {
      fact: "Octopuses have three hearts: two pump blood to the gills, while the third pumps it to the rest of the body.",
      hint: "Did you know that octopuses have multiple hearts?",
      isTrue: true,
      distractor: "Octopuses have a single central heart and eight mini-hearts in each tentacle.",
      source: "https://www.nationalgeographic.com/animals/invertebrates/facts/octopuses",
      citation: "National Geographic: Octopus Profile"
    },
    {
      fact: "Octopus blood is blue because it uses a copper-rich protein called hemocyanin to transport oxygen, which is more efficient in cold, low-oxygen water.",
      hint: "Did you know that octopus blood is a very unusual color?",
      isTrue: true,
      distractor: "Octopus blood is yellow due to a high concentration of sulfur-based proteins.",
      source: "https://www.scientificamerican.com/article/why-is-octopus-blood-blue/",
      citation: "Scientific American: Octopus Blue Blood"
    },
    {
      fact: "Two-thirds of an octopus's neurons are located in its arms, not its head, meaning their arms can taste, touch, and act independently.",
      hint: "Did you know that most of an octopus's brain capacity is distributed outside its head?",
      isTrue: true,
      distractor: "Octopuses have nine brains, with one dedicated brain in the tip of each tentacle.",
      source: "https://www.nhm.ac.uk/discover/octopuses-keep-surprising-us.html",
      citation: "Natural History Museum: Octopus Neurons"
    },
    {
      fact: "Female octopuses are semelparous, meaning they reproduce once and then undergo a programmed cellular decline leading to death shortly after eggs hatch.",
      hint: "Did you know that reproduction is a fatal event for mother octopuses?",
      isTrue: true,
      distractor: "Female octopuses shed their outer skin layers like snakes after laying eggs.",
      source: "https://www.livescience.com/why-mother-octopuses-die-after-eggs-hatch.html",
      citation: "Live Science: Why Mother Octopuses Die"
    },
    {
      fact: "The Mimic Octopus can change its color, texture, and behavior to impersonate sea snakes, lionfish, and flatfish to deter specific predators.",
      hint: "Did you know there is an octopus that can impersonate multiple toxic sea animals?",
      isTrue: true,
      distractor: "The Mimic Octopus copies the songs of whales to lure fish into reef crevices.",
      source: "https://www.nationalgeographic.com/animals/invertebrates/facts/mimic-octopus",
      citation: "National Geographic: Mimic Octopus"
    }
  ],
  "black holes": [
    {
      fact: "If you fell into a stellar-mass black hole, gravity would pull much harder on your feet than your head, stretching you out like spaghetti—a real physics term called 'spaghettification'.",
      hint: "Did you know there is a culinary-inspired physics term for falling into a black hole?",
      isTrue: true,
      distractor: "Falling into a black hole would compress your body into a perfect two-dimensional sheet.",
      source: "https://science.nasa.gov/universe/black-holes/",
      citation: "NASA: Black Holes Guide"
    },
    {
      fact: "Black holes are not completely black; they emit a faint thermal radiation known as Hawking radiation due to quantum effects near the event horizon.",
      hint: "Did you know that black holes actually leak energy and will eventually evaporate?",
      isTrue: true,
      distractor: "Black holes emit pulses of gamma rays in a sequence that matches prime numbers.",
      source: "https://www.space.com/hawking-radiation",
      citation: "Space.com: Hawking Radiation Explained"
    },
    {
      fact: "The closest known black hole to Earth, Gaia BH1, is only 1,560 light-years away in the constellation Ophiuchus.",
      hint: "Did you know there is a black hole practically in our cosmic backyard?",
      isTrue: true,
      distractor: "The closest black hole is orbiting the star Proxima Centauri, just 4 light-years away.",
      source: "https://www.nasa.gov/image-article/gaia-bh1-closest-black-hole-to-earth/",
      citation: "NASA: Gaia BH1 Discovery"
    },
    {
      fact: "Time slows down near a black hole due to gravitational time dilation; to an outside observer, you would appear to freeze at the event horizon and slowly fade.",
      hint: "Did you know that time behaves extremely strangely as you approach a black hole?",
      isTrue: true,
      distractor: "Inside a black hole, time runs in reverse, making objects younger as they get closer.",
      source: "https://hubblesite.org/contents/articles/black-holes",
      citation: "Hubble Site: Gravity and Time"
    },
    {
      fact: "Supermassive black holes can power 'quasars', which are so bright they can outshine entire galaxies containing hundreds of billions of stars.",
      hint: "Did you know that the space around a black hole can be the brightest object in the universe?",
      isTrue: true,
      distractor: "Supermassive black holes generate dark energy, which repels stars and splits galaxies.",
      source: "https://science.nasa.gov/universe/galaxies/quasars/",
      citation: "NASA: What are Quasars?"
    }
  ]
};

// Generic Fallback Facts Generator for any other topic
function getGenericFallbackFacts(topic) {
  const cleanTopic = topic.charAt(0).toUpperCase() + topic.slice(1).toLowerCase();
  return [
    {
      fact: `The word '${cleanTopic}' has historical roots tracing back through centuries, evolving in definition as language and scientific understanding grew.`,
      hint: `Did you know the term '${cleanTopic}' has a long and surprising linguistic history?`,
      isTrue: true,
      distractor: `The word '${cleanTopic}' was invented in 1998 by a software engineer in Silicon Valley.`,
      source: "https://www.etymonline.com/",
      citation: "Online Etymology Dictionary"
    },
    {
      fact: `Scientific studies on '${cleanTopic}' have accelerated in the last decade, revealing complex internal properties that differ significantly from early models.`,
      hint: `Did you know that our understanding of '${cleanTopic}' changed completely in recent years?`,
      isTrue: true,
      distractor: `Under high pressure, '${cleanTopic}' turns into a liquid metal that conducts electricity.`,
      source: "https://www.wikipedia.org/",
      citation: "Wikipedia: Scientific Research"
    },
    {
      fact: `Architectural and structural elements associated with '${cleanTopic}' display unique geometric ratios that optimize stability and surface area.`,
      hint: `Did you know that '${cleanTopic}' follows a specific mathematical pattern?`,
      isTrue: true,
      distractor: `All instances of '${cleanTopic}' globally conform to the exact Golden Ratio of 1.618.`,
      source: "https://mathworld.wolfram.com/",
      citation: "Wolfram MathWorld"
    },
    {
      fact: `Environmental researchers have discovered that '${cleanTopic}' reacts uniquely to extreme temperatures, demonstrating remarkable thermal resilience.`,
      hint: `Did you know that '${cleanTopic}' can survive extreme environmental changes?`,
      isTrue: true,
      distractor: `If exposed to absolute zero, '${cleanTopic}' immediately turns into a gaseous state.`,
      source: "https://www.nature.com/",
      citation: "Nature Environmental Research"
    },
    {
      fact: `Standard cultural references to '${cleanTopic}' vary wildly across the globe, with some societies treating it as a symbol of luck and others as a warning.`,
      hint: `Did you know that '${cleanTopic}' represents completely opposite concepts in different cultures?`,
      isTrue: true,
      distractor: `In ancient Rome, it was illegal to speak the word '${cleanTopic}' during a solar eclipse.`,
      source: "https://www.britannica.com/",
      citation: "Encyclopaedia Britannica: Culture"
    }
  ];
}

/**
 * Fetches 5 niche facts for a topic using Google Search Grounding.
 * Falls back to mock database if API fails, is missing, or for offline use.
 */
async function fetchNicheFacts(topic) {
  const normalizedTopic = topic.trim().toLowerCase();

  // 4. Never call Gemini if USE_MOCK_DATA=true
  if (process.env.USE_MOCK_DATA === "true") {
    return MOCK_FACTS[normalizedTopic] || [];
  }

  const apiKey = process.env.GEMINI_API_KEY;

  // If API key is missing, go straight to fallback
  if (!apiKey || apiKey === "your_gemini_api_key_here") {
    console.warn("GEMINI_API_KEY is not configured. Using fallback mock data.");
    return MOCK_FACTS[normalizedTopic] || [];
  }

  console.log("[Gemini Call]", topic);

  try {
    const ai = new GoogleGenAI({ apiKey });
    const prompt = `Find 5 extremely niche, verified, lesser-known facts about "${topic}".

Requirements:
- Facts must be surprising and verifiable.
- Include real source URLs when available.
- Avoid generic facts.
- Return ONLY valid JSON.
- Do not include markdown fences.

Return exactly:

[
  {
    "fact": "string",
    "hint": "string",
    "isTrue": true,
    "distractor": "string",
    "source": "https://...",
    "citation": "Source Name"
  }
]`;

    const response = await ai.models.generateContent({
      model: "gemini-2.5-flash",
      contents: prompt,
      config: {
        tools: [{ googleSearch: {} }],
      }
    });

    if (!response || !response.text) {
      throw new Error("Empty response received from Gemini API.");
    }

    const cleaned = response.text
      .replace(/```json/g, "")
      .replace(/```/g, "")
      .trim();

    let facts;
    try {
      facts = JSON.parse(cleaned);
    } catch (parseError) {
      throw new Error(`Failed to parse Gemini JSON response: ${parseError.message}`);
    }

    if (!Array.isArray(facts) || facts.length === 0) {
      throw new Error("Gemini API response did not parse as a non-empty array.");
    }

    console.log("[Gemini Success]", topic);
    return facts;
  } catch (error) {
    console.error(`Gemini API Error for topic '${topic}':`, error.message);
    console.log("[Gemini Fallback]", topic);
    return MOCK_FACTS[normalizedTopic] || [];
  }
}

module.exports = {
  fetchNicheFacts
};
